server:
  port: 8099

spring:
  application:
    name: APPLYSEARCH

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8081/eureka/
    register-fetch-interval-seconds: 30